# Copyright 2019 ProximaX Limited. All rights reserved.
# Use of this source code is governed by the Apache 2.0
# license that can be found in the LICENSE file.

language: java

jdk:
  - openjdk8

before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi
  # - chmod +x .travis/deploy.sh # giving execution permissions to this file to avoid error 127.
  # - mv ./.travis ../ # moving this out the publication folder as we don't want to publish it.

install: 
  - echo 'Skip default Travis CI install step' # this is to avoid an error with pub in Travis

jobs:
  include:
    - stage: publish snapshot
      if: type = push AND branch = master
      script:
        - echo "Publishing snapshot"
        - mvn deploy --settings .travis/settings.xml -B -U
    - stage: prepare release
      if: tag IS present
      script:
        - echo "Publishing release $TRAVIS_TAG to public repository"
        - mvn --settings .travis/settings.xml org.codehaus.mojo:versions-maven-plugin:2.1:set -DnewVersion=$TRAVIS_TAG 1>/dev/null 2>/dev/null
        - mvn deploy --settings .travis/settings.xml -B -U
